### ISSUE TITLE
Simulation model only work once

### ISSUE THREAD

**Issue by masteryijian** [PyLinX-Project/PyLinX#23]
After i close the Simulation once, can i no more open it again, and this will show:
Traceback (most recent call last):
  File "E:\Master\3. Programm\PyLinX\__init__.py", line 341, in on_Activate_Simulation_Mode
    self.mainController.execCommand(u"@mainController set bSimulationMode True")
  File "E:\Master\3. Programm\PyLinX\PyLinXCtl\PyLinXController.py", line 177, in execCommand
    return self.__execCommand_set(context, command[1:])
  File "E:\Master\3. Programm\PyLinX\PyLinXCtl\PyLinXController.py", line 290, in __execCommand_set
    return context.set(command[0], command[1])
  File "E:\Master\3. Programm\PyLinX\PyLinXData\BContainer.py", line 175, in set
    _type._dictSetCallbacks[attr](self,setObj, options)
  File "E:\Master\3. Programm\PyLinX\PyLinXCtl\PyLinXProjectController.py", line 249, in set_bSimulationMode
    rootGraphics.recur(PyLinXData.PyLinXCoreDataObjects.PX_PlottableVarDispElement, u"widgetShow", ())
  File "E:\Master\3. Programm\PyLinX\PyLinXData\BContainer.py", line 488, in recur
    element.recur(typeinfo, strFunction, tupleArgs, bSubTypes)
  File "E:\Master\3. Programm\PyLinX\PyLinXData\BContainer.py", line 484, in recur
    exec(strExec)
  File "<string>", line 1, in <module>
  File "E:\Master\3. Programm\PyLinX\PyLinXData\PyLinXCoreDataObjects.py", line 1097, in widgetShow
    bVarDispVisible = self.get(u"bVarDispVisible")
  File "E:\Master\3. Programm\PyLinX\PyLinXData\BContainer.py", line 127, in get
    return self.__Attributes[attr]
KeyError: u'bVarDispVisible'

**Comment by WaetzoldP** [comment]
fixed
